BEGIN DEFERRED;
INSERT INTO plots (plot) VALUES ( 'Supplication' );
INSERT INTO plots (plot) VALUES ( 'Deliverance' );
INSERT INTO plots (plot) VALUES ( 'Crime pursued by vengeance' );
INSERT INTO plots (plot) VALUES ( 'Vengeance taken for kin upon kin' );
INSERT INTO plots (plot) VALUES ( 'Pursuit' );
INSERT INTO plots (plot) VALUES ( 'Disaster' );
INSERT INTO plots (plot) VALUES ( 'Falling prey to cruelty/misfortune' );
INSERT INTO plots (plot) VALUES ( 'Revolt' );
INSERT INTO plots (plot) VALUES ( 'Daring enterprise' );
INSERT INTO plots (plot) VALUES ( 'Abduction' );
INSERT INTO plots (plot) VALUES ( 'The enigma' );
INSERT INTO plots (plot) VALUES ( 'Obtaining' );
INSERT INTO plots (plot) VALUES ( 'Enmity of kin' );
INSERT INTO plots (plot) VALUES ( 'Rivalry of kin' );
INSERT INTO plots (plot) VALUES ( 'Murderous adultery' );
INSERT INTO plots (plot) VALUES ( 'Madness' );
INSERT INTO plots (plot) VALUES ( 'Fatal imprudence' );
INSERT INTO plots (plot) VALUES ( 'Involuntary crimes of love' );
INSERT INTO plots (plot) VALUES ( 'Slaying of kin unrecognized' );
INSERT INTO plots (plot) VALUES ( 'Self-sacrifice for an ideal' );
INSERT INTO plots (plot) VALUES ( 'Self-sacrifice for kin' );
INSERT INTO plots (plot) VALUES ( 'All sacrificed for passion' );
INSERT INTO plots (plot) VALUES ( 'Necessity of sacrificing loved ones' );
INSERT INTO plots (plot) VALUES ( 'Rivalry of superior vs. inferior' );
INSERT INTO plots (plot) VALUES ( 'Adultery' );
INSERT INTO plots (plot) VALUES ( 'Crimes of love' );
INSERT INTO plots (plot) VALUES ( 'Discovery of the dishonour of a loved one' );
INSERT INTO plots (plot) VALUES ( 'Obstacles to love' );
INSERT INTO plots (plot) VALUES ( 'An enemy loved' );
INSERT INTO plots (plot) VALUES ( 'Ambition' );
INSERT INTO plots (plot) VALUES ( 'Conflict with a god' );
INSERT INTO plots (plot) VALUES ( 'Mistaken jealousy' );
INSERT INTO plots (plot) VALUES ( 'Erroneous judgment' );
INSERT INTO plots (plot) VALUES ( 'Remorse' );
INSERT INTO plots (plot) VALUES ( 'Recovery of a lost one' );
INSERT INTO plots (plot) VALUES ( 'Loss of loved ones' );
INSERT INTO plots (plot) VALUES ( 'Overcoming the Monster' );
INSERT INTO plots (plot) VALUES ( 'Rags to Riches' );
INSERT INTO plots (plot) VALUES ( 'The Quest' );
INSERT INTO plots (plot) VALUES ( 'Voyage and Return' );
INSERT INTO plots (plot) VALUES ( 'Comedy' );
INSERT INTO plots (plot) VALUES ( 'Tragedy' );
INSERT INTO plots (plot) VALUES ( 'Rebirth' );
INSERT INTO plots (plot) VALUES ( 'Precursors' );
END;
