#version "3.9"

services:

    web:
      build: docker/django
      image: python:3.12.0-alpine3.18
      hostname: cb
      ports:  
        - "8000:8000"
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
        - ./docker/django/code:/code
      networks:
        network:
          ipv4_address: 10.0.0.10
      depends_on:
        - db

    db:
        image: postgres:16.1-alpine3.18
        hostname: cb_postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        ports:
            - "5432:5432"
        networks:
          network:
            ipv4_address: 10.0.0.5


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1

