BEGIN DEFERRED;
INSERT INTO cultures (idx, culture) VALUES ( 1, 'Clan' );
INSERT INTO cultures (idx, culture) VALUES ( 2, 'Coaster' );
INSERT INTO cultures (idx, culture) VALUES ( 3, 'Desert Tribe' );
INSERT INTO cultures (idx, culture) VALUES ( 4, 'Guide' );
INSERT INTO cultures (idx, culture) VALUES ( 5, 'Path' );
INSERT INTO cultures (idx, culture) VALUES ( 6, 'Mountain Man' );
INSERT INTO cultures (idx, culture) VALUES ( 7, 'Navy' );
INSERT INTO cultures (idx, culture) VALUES ( 8, 'Army' );
INSERT INTO cultures (idx, culture) VALUES ( 9, 'Noble' );
INSERT INTO cultures (idx, culture) VALUES ( 10, 'Northern Territory' );
INSERT INTO cultures (idx, culture) VALUES ( 11, 'Marine' );
INSERT INTO cultures (idx, culture) VALUES ( 12, 'Dragon' );
INSERT INTO cultures (idx, culture) VALUES ( 13, 'Firster' );
INSERT INTO cultures (idx, culture) VALUES ( 14, 'Old Guard' );
INSERT INTO cultures (idx, culture) VALUES ( 15, 'Spacer' );
INSERT INTO cultures (idx, culture) VALUES ( 16, 'Atrean' );
INSERT INTO cultures (idx, culture) VALUES ( 17, 'Star Confederation' );
INSERT INTO cultures (idx, culture) VALUES ( 18, 'Haearn' );
INSERT INTO cultures (idx, culture) VALUES ( 19, 'Pirate' );
INSERT INTO cultures (idx, culture) VALUES ( 20, 'Mobile' );
INSERT INTO cultures (idx, culture) VALUES ( 21, 'Merchant' );
END;
