BEGIN DEFERRED;
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Romero", 'Cecil', 'M', 1413242, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Rich", 'Coy', 'M', 1413306, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Thuillier", 'Evalyn', 'F', 1414249, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Stanley", 'Jacelyn', 'F', 1414323, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "McKenna", 'Diedre', 'F', 1418181, "Desert Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Kristensen", 'Emiko', 'F', 1415003, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "MacDonald", 'Hugh', 'M', 1415228, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Romero", 'Katherine', 'F', 1415305, "Trouble Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Daniel", 'Man', 'M', 1416218, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Riou", 'Kasey', 'M', 1416149, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Verstraeten", 'Romona', 'F', 1416237, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Swenson", 'Erk', 'M', 1416209, "Dede's boyfriend, Lennert's son. Talking Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "McPherson", 'Kyle', 'M', 1416184, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Mullen", 'Georgiann', 'F', 1416334, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Holmgren", 'Hugh', 'M', 1416151, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Madden", 'Jae', 'M', 1416078, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Floyd", 'Devora', 'F', 1416243, "Forest Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Tate", 'Kenneth', 'M', 1416116, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Fekete", 'Bart', 'M', 1416047, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Chapman", 'Rosann', 'F', 1416307, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Legras", 'Donovan', 'M', 1416076, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Hurley", 'Nigel', 'M', 1416074, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Levasseur", 'Apryl', 'F', 1416038, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Berntsen", 'Trista', 'F', 1416288, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Launay", 'Rebecka', 'F', 1416211, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Turner", 'Haywood', 'M', 1416042, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Nyman", 'Marcos', 'M', 1416049, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Guibert", 'Lonny', 'M', 1416056, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Winters", 'Janay', 'F', 1416250, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Raymond", 'Jesse', 'F', 1416143, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Ferre", 'Virgina', 'F', 1416131, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Webb-Marston", 'Anwyn', 'F', 1416312, "Bilge Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Preston", 'Shelia', 'F', 1416322, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Laval", 'Jolyn', 'F', 1416265, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Ferrier", 'Cherryl', 'F', 1416146, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Goossens", 'Benedict', 'M', 1416101, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Casey", 'Joana', 'F', 1416029, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Gosset", 'Nicky', 'M', 1416122, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Jacobson", 'Lucie', 'F', 1416161, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Jensen", 'Alpha', 'F', 1416030, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Roux", 'Foster', 'M', 1416210, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bob", 'Sachiko', 'F', 1416305, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Ottoson", 'Tindra', 'F', 1416191, "Tinny Guardian Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Finch", 'Josephina', 'F', 1416168, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Reed", 'Ivey', 'F', 1416060, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Maes", 'Jerome', 'M', 1416293, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Pham", 'Clarence', 'M', 1416251, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Sandoval", 'Essie', 'F', 1416152, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lee", 'Yesenia', 'F', 1416087, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "McKee", 'Armand', 'M', 1416205, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Weeks", 'Leon', 'M', 1416167, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lefevre", 'Brittany', 'F', 1416218, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Woodward", 'Marty', 'M', 1416146, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Király", 'Philomena', 'F', 1416144, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Genin", 'Carter', 'M', 1416072, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bennet", 'Isela', 'F', 1414175, "Lost Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bourdin", 'Randy', 'M', 1416287, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Meyers", 'Kum', 'F', 1416034, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Pauwels", 'Ricky', 'M', 1416018, "Loyal Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Myklebust", 'Ronny', 'M', 1416296, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Rossi", 'Myra', 'F', 1416048, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Joly", 'Clarisa', 'F', 1415168, "NPG" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lienard", 'Willian', 'M', 1416301, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Dias", 'Magaly', 'F', 1416009, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Davidson", 'Dalila', 'F', 1416334, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Remond", 'Kattie', 'F', 1416265, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Colon", 'Emery', 'M', 1416096, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bauer", 'Werner', 'M', 1416316, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Auvray", 'Tim', 'M', 1416092, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Ramirez", 'Antwan', 'M', 1416127, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Murphy", 'Keven', 'M', 1416237, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Viard", 'Marry', 'F', 1416015, "NPG" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Michaux", 'Milan', 'M', 1416129, "Quiet Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Wilkinson", 'Lashonda', 'F', 1416016, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lyons", 'Lewis', 'M', 1416230, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Villette", 'Yessenia', 'F', 1416075, "NPG" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Biró", 'Freddie', 'M', 1416198, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "England", 'Art', 'M', 1416108, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Rodriguez", 'Demetrius', 'M', 1416196, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Moran", 'Nadia', 'F', 1416334, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Garin", 'Amelia', 'F', 1416201, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Stokes", 'Arletha', 'F', 1416308, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Guerra", 'Melvin', 'F', 1416172, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bianchi", 'Shonta', 'F', 1416250, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Hansson", 'Willie', 'M', 1416314, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Marchal", 'Amalia', 'F', 1416161, "NPG" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Allen", 'Jerrod', 'M', 1416340, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Horton", 'Shenna', 'F', 1416319, "NPG" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Gonzalez", 'Fatimah', 'F', 1416288, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Combes", 'Lee', 'M', 1416039, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Aune", 'Angelo', 'M', 1416058, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "McPherson", 'Alisa', 'F', 1416076, "PigTail, Hidden Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Graelean", 'Robert', 'M', 1416210, "Bobby, gray-green eyes, wavy black hair." );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Whitley", 'Illa', 'F', 1416289, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "MacLeod", 'Regan', 'F', 1416092, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lamour", 'Annis', 'F', 1416294, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Romero", 'Rosalie', 'F', 1416126, "Beach Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Chang", 'Troy', 'M', 1416358, "Bobby's Team (1429.4)" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Szücs", 'Divina', 'F', 1416132, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Briere", 'Regan', 'F', 1416357, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Armstrong", 'Stanford', 'M', 1416071, "Driven Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Herve", 'Gil', 'M', 1416007, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Leroux", 'Von', 'M', 1416163, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Frye", 'Merry', 'F', 1416293, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bradley", 'Milan', 'M', 1416017, "Bobby's Team (1429.4)" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Fry", 'Antonia', 'F', 1416282, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Bourdon", 'Shira', 'F', 1416316, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Hendrickx", 'Roma', 'F', 1416341, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Humbert", 'Hsiu', 'F', 1416009, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Thiery", 'Pasquale', 'M', 1416145, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Jouan", 'Madelene', 'F', 1416086, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Richardson", 'Loralee', 'F', 1416323, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Cooke", 'Darrell', 'M', 1416072, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Thompson", 'Rene', 'M', 1416029, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Hardy", 'Joey', 'M', 1416302, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Salaun", 'Pat', 'M', 1416282, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Conner", 'Myron', 'M', 1416259, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lefron", 'Wilbur', 'M', 1416075, "Gimpy Rat" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lester", 'Clarissa', 'F', 1416081, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Rønning", 'Angeles', 'F', 1416108, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Garrison", 'Laureen', 'F', 1416039, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Lester", 'Carroll', 'M', 1416158, "" );
INSERT INTO people ( last_name, first_name, gender, birthdate, notes) VALUES ( "Domici", 'Alba', 'F', 1416146, "Trail Rat" );
END;
